### ISSUE TITLE
text editor example

### ISSUE THREAD

**Issue by JerryFox** [webui-dev/python-webui#6]
C:\Users\vysok\python\python-webui\examples\text-editor>python main.py
Traceback (most recent call last):
  File "C:\Users\vysok\python\python-webui\examples\text-editor\main.py", line 25, in <module>
    main()
  File "C:\Users\vysok\python\python-webui\examples\text-editor\main.py", line 16, in main
    window.set_root_folder("ui/")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'window' object has no attribute 'set_root_folder'

Where is the problem???

Thanks! 

Jaroslav Vysoký
Czech Republic

**Comment by AlbertShown** [comment]
@hassandraga PyPi package needs to be updated.

**Comment by JerryFox** [comment]
Thanks! I did it already. 

J.

**Comment by kvbik** [comment]
Hey @AlbertShown - instead of copy the `webui.py` file, it is better practice for local development to do:

`pip install -e .`

The main trick is to do it from the directory where the `setup.py` or `pyproject.toml` is. Which in this case is `PyPI/Package/`.
